language : node_js
# sudo=false to run builds inside container infrastructure
# see https://github.com/bem/bem-components/issues/1528
sudo: false

node_js:
  - "8"
cache:
  directories:
    - "node_modules"


before_script:
    - "npm install -g npm@5.7"
    - "npm i"

script:
    - npm run unit

env:
  global:
    - GH_REF: github.com/appwilio/ap-components.git
    - ISTANBUL_COVERAGE: yes
