language : node_js
# sudo=false to run builds inside container infrastructure
# see https://github.com/bem/bem-components/issues/1528
sudo: false

node_js:
  - "0.12"

before_script:
    - npm install

script:
    - npm run unit

env:
  global:
    - GH_REF: github.com/appwilio/ap-components.git
    - ISTANBUL_COVERAGE: yes
